language: php
dist: trusty
sudo: required
group: deprecated-2017Q4

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:

  # - phpenv config-rm xdebug.ini || true

  # initialize databases
  - mysql -u root -e "CREATE DATABASE homestead;"
  - mysql -u root -e "CREATE USER 'homestead'@'%' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'homestead'@'%' WITH GRANT OPTION;"

install:

  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - sudo chmod -R 777 storage
  - cp .env.example .env

  # show some versions and env information
  - mysql --version
  - php --version
  - composer --version

  - php artisan migrate --env=local --database=homestead --no-interaction -vvv
  - php artisan db:seed --env=local --no-interaction -vvv

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=storage/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=clover storage/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
