name: PHPUnit

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  phpunit:
    name: tests

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          MYSQL_DATABASE: dbname

    steps:
    - name: Set up MySQL
      run: |
        sudo mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - uses: actions/checkout@v1
    - uses: carlosabcs/lumen-phpunit-action@master
